export const BASE_URL = 'http://localhost:4000';

export const LOCAL_AUTH_ID = 'local_auth_id';
export const USER = {
  token: null,
};

export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const GET_ACTIVE_COURSES_START = 'GET_ACTIVE_COURSES_START';
export const GET_ACTIVE_COURSES_SUCCESS = 'GET_ACTIVE_COURSES_SUCCESS';
export const GET_ACTIVE_COURSES_FAILED = 'GET_ACTIVE_COURSES_FAILED';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const GROUP_GET_START = 'GROUP_GET_START';
export const GROUP_GET_SUCCESS = 'GROUP_GET_SUCCESS';
export const GROUP_GET_FAILED = 'GROUP_GET_FAILED';
export const GROUP_ADD_SUCCESS = 'GROUP_ADD_SUCCESS';
export const GROUP_ADD_FAILED = 'GROUP_ADD_FAILED';
export const GROUP_UPDATE_SUCCESS = 'GROUP_UPDATE_SUCCESS';
export const GROUP_UPDATE_FAILED = 'GROUP_UPDATE_FAILED';

export const RESET_GROUP = 'RESET_GROUP';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
